name: "toydataset"
train_path: "/project/lt200349-cu-sls/dataset/binaural_speech_enhancement/toyd
ataset/train"
val_path: "/project/lt200349-cu-sls/dataset/binaural_speech_enhancement/toydat
aset/test"
test_path: "/project/lt200349-cu-sls/dataset/binaural_speech_enhancement/toyda
taset/test"
mode: "both"
batch_size: 32
num_workers: 4