name: "toydataset"
train_path: "/project/lt200349-cu-sls/dataset/binaural_speech_enhancement/toydataset/train"
val_path: "/project/lt200349-cu-sls/dataset/binaural_speech_enhancement/toydataset/test"
test_path: "/project/lt200349-cu-sls/dataset/binaural_speech_enhancement/toydataset/test"
mode: "both"
batch_size: 32
num_workers: 4